### ISSUE TITLE
Camera Utils Update

### ISSUE THREAD

**Issue by aymericmariaux** [MythMega/mysurvivalmods#38]
Camera Utils 1.05 is available (https://modrinth.com/mod/camera-utils/version/fabric-1.20.1-1.0.5)

**Comment by aymericmariaux** [comment]
https://cdn.modrinth.com/data/rrwQMaWQ/versions/Hlt5l77f/camerautils-1.20.1-1.0.5.jar

**Comment by MythMega** [comment]
already available in current version of MSM
