### ISSUE TITLE
Chat Heads Update

### ISSUE THREAD

**Issue by aymericmariaux** [MythMega/mysurvivalmods#39]
Chat Heads 0.10.20 is available (https://modrinth.com/mod/chat-heads/version/CJCClsCd)

**Comment by aymericmariaux** [comment]
https://cdn.modrinth.com/data/Wb5oqrBJ/versions/CJCClsCd/chat_heads-0.10.20-fabric-1.20.jar

**Comment by MythMega** [comment]
already available in current version of MSM
