### ISSUE TITLE
Continuity Update

### ISSUE THREAD

**Issue by aymericmariaux** [MythMega/mysurvivalmods#40]
Continuity v3.0.0-beta.3+1.20.1 is available (https://modrinth.com/mod/continuity/version/3.0.0-beta.3+1.20.1)

**Comment by aymericmariaux** [comment]
Need indium maybe the last version who need sodium 5.0 who is not compatible with ChunksFadeIn yet.

**Comment by aymericmariaux** [comment]
https://cdn.modrinth.com/data/1IjD5062/versions/xy2co4Rh/continuity-3.0.0-beta.3%2B1.20.1.jar

**Comment by MythMega** [comment]
already available in current version of MSM
