### ISSUE TITLE
Fabric Language Kotlin Update

### ISSUE THREAD

**Issue by aymericmariaux** [MythMega/mysurvivalmods#41]
Fabric Language Kotlin 1.10.8+kotlin.1.9.0 is now available (https://modrinth.com/mod/fabric-language-kotlin/version/1.10.8+kotlin.1.9.0)

**Comment by aymericmariaux** [comment]
https://cdn.modrinth.com/data/Ha28R6CL/versions/s10JMAtS/fabric-language-kotlin-1.10.8%2Bkotlin.1.9.0.jar

**Comment by MythMega** [comment]
already available in current version of MSM
