### ISSUE TITLE
Falling Leaves Update

### ISSUE THREAD

**Issue by aymericmariaux** [MythMega/mysurvivalmods#42]
Falling Leaves v1.15.2 is now available (https://modrinth.com/mod/fallingleaves/version/1.15.2+1.20.1)

**Comment by aymericmariaux** [comment]
https://cdn.modrinth.com/data/WhbRG4iK/versions/8qK6ANpJ/fallingleaves-1.15.2%2B1.20.1.jar

**Comment by MythMega** [comment]
already available in current version of MSM
