### ISSUE TITLE
(de)activating mods windows

### ISSUE THREAD

**Issue by aymericmariaux** [MythMega/mysurvivalmods#51]
When activating or deactivating mods, cmd windows appear on some computer.
![image](https://github.com/MythMega/mysurvivalmods/assets/94635911/d512b33e-f46d-4caa-9184-1c806a6b0703)

**Comment by MythMega** [comment]
​
Fixe TODO :

        ProcessStartInfo startInfo = new ProcessStartInfo
        {
            FileName = "cmd.exe",
            RedirectStandardInput = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        Process process = new Process
        {
            StartInfo = startInfo
        };

        process.Start();

        using (StreamWriter sw = process.StandardInput)
        {
            if (sw.BaseStream.CanWrite)
            {
                sw.WriteLine($"\"{filePath}\"");
            }
        }

        process.WaitForExit();
        process.Close();

**Comment by MythMega** [comment]
Fixe :

        ProcessStartInfo startInfo = new ProcessStartInfo
        {
            FileName = "cmd.exe",
            RedirectStandardInput = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        Process process = new Process
        {
            StartInfo = startInfo
        };

        process.Start();

        using (StreamWriter sw = process.StandardInput)
        {
            if (sw.BaseStream.CanWrite)
            {
                sw.WriteLine($"\"{filePath}\"");
            }
        }

        process.WaitForExit();
        process.Close();

Le mar. 15 août 2023 à 14:41, AymericOwer ***@***.***> a
écrit :

**Comment by MythMega** [comment]
corrigé version 1.1
